# Use new container based environment
sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - develop

matrix:
    fast_finish: true

    include:
        # aliased to a recent 7.0 version
        - php: '7.0'
        # aliased to a recent 7.1 version
        - php: '7.1'
          env: SNIFF=1
        # aliased to a recent 7.2 version
        - php: '7.2'
        # php nightly
        - php: 'nightly'

    allow_failures:
        - php: nightly

install:
  - composer install
  - composer dump-autoload -o

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ "$SNIFF" == "1" ]]; then composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs; fi

script:
  # runs phpcs with the rules from the project, allow warnings not to cause fail.
  - if [[ "$SNIFF" == "1" ]]; then phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php') --runtime-set ignore_warnings_on_exit 1; fi
